### ISSUE TITLE
No reboot necessary, only systemctl start keychron

### ISSUE THREAD

**Issue by Helbis** [adam-savard/keychron-k2-function-keys-linux#10]
I didn't do a full reboot of the machine, only
`sudo systemctl start keychron`

Maybe it is worth it to add it to the **README** in the STEP 4, as an alternative.

**Comment by adam-savard** [comment]
While yes, you can absolutely do as you say here, the main point of the script is the changes persisting after a reboot. 

As that's the case, I think it's more important to keep things the way they are. Linux is powerful in that you can modify the system while it's running, but whenever a change like this is made you should _always_ reboot to make sure.
