### ISSUE TITLE
Does not work in fedora

### ISSUE THREAD

**Issue by Renegade13Code** [adam-savard/keychron-k2-function-keys-linux#17]
I am running fedora 35. I have followed the specified procedure. The created systemd service (`keychron.service`), runs correctly when the keyboard is plugged in on startup. It appears however that if the system has already booted and then the keyboard is connected via Bluetooth then the service does not run i.e. change `fnmode` to 0. How can i ensure that the service runs every time the keyboard is connected?

**Comment by adam-savard** [comment]
That's a good question! I always kept the keyboard plugged in, so I never tried bluetooth.

I imagine what you'd be able to do, though, is set up a hook whenever a device connects via bluetooth and have that run. As to how to do so, not exactly sure!

**Comment by adam-savard** [comment]
I'm going to close this issue, but I have a suggestion you could try: run the keyboard in Mac mode, and that should alleviate some of the issues you experience.
