### ISSUE TITLE
Context: Windows and/or Mac

### ISSUE THREAD

**Issue by PeterMortensen** [adam-savard/keychron-k2-function-keys-linux#22]
Does this depend on the keyboard being in Mac mode (the switch at the back/at the left)? If so, perhaps mention that on the page?

Or even mention it in any case, whether the switch at the back/at the left is supposed to be in a particular position or not.

---------

(I discovered the page through [a Reddit comment](https://www.reddit.com/r/Keychron/comments/ktzmhj/keychron_k6_problem_with_ubuntu_2010/).)

(I am on Linux 100% and am willing to test stuff, but that is with Keychron V and Keychron K Pro series ***full-sized*** keyboards ([QMK](https://docs.qmk.fm/#/faq_general?id=what-is-qmk)-based only), so it probably doesn't apply. I have about seven months experience with Keychron keyboards (incl. implementing a custom macro execution engine to allow cancelling macros in progress), but I repurposed an old Apple [AEKII](https://www.youtube.com/watch?v=QDMQH-EoCK8) some years ago to use QMK (based on AVR / [Arduino Micro](https://store.arduino.cc/collections/boards/products/arduino-micro)).)

**Comment by adam-savard** [comment]
Hi! The keyboard actually doesn't need to be in mac mode. It probably doesn't hurt for it to be on the readme, in that sense.

When I was using it, it was in Windows mode; I prefer my keyboards to work in that mode. I tried mac mode, but I don't remember if the fix was compatible with it?

----

EDIT:

I've added a line to say that the steps for Keychron keyboards were tested in Windows mode! If you have any other suggestions, I'm happy to implement them!

**Comment by PeterMortensen** [comment]
> The keyboard actually doesn't need to be in mac mode

Yes, it probably doesn't make a difference for that particular keyboard ([Keychron K6](https://cdn.shopify.com/s/files/1/0059/0630/1017/files/k6_user_manual_english_version-compressed.pdf?v=1609225495)) as there are two Fn keys on it, ***Fn1*** and ***Fn2***. Presumably they work the same way wrt. F1-F12/media keys for both Windows and Mac. The Windows/Mac setting by the switch on the left of the keyboard may only affect the key code to the right of the space bar (right alt (AltGr) for Windows and Ctrl for Mac).

Whereas, for example, on the [Keychron K4](https://www.keychron.com/pages/k4-keyboard-user-manual) (96%) whether a media key needs modifier key ***Fn*** or not to activate depends on the Windows/Mac setting by the switch on the left of the keyboard. The same for the F1-F12 keys, whether modifier key ***Fn*** is needed or not for them to activate. Presumably, it is F1-F12 not requiring modifier key ***Fn*** in Windows mode and media keys not requiring modifier key ***Fn*** in Mac mode (the manual is too terse). That is, it probably does make a difference for Keychron K4. It is apparently also possible to switch between the two modes by holding ***Fn*** + ***X*** + ***L*** down for 4 seconds.

**Comment by PeterMortensen** [comment]
> were tested in Windows mode

I think that is sufficient to state.

Though a stronger statement would be that this (Linux configuration change) ***only*** works in Windows mode (by the switch on the side/back of the Keychron keyboard) for ***Keychron keyboards A, B, and C***, but for ***Keychron keyboards X, Y, and Z*** the Keychron keyboard switch setting ***doesn't matter*** for it (the Linux configuration change). Presuming that is actually the case (I don't have any means of testing the statement). But that may be too much trouble.

Or I might be completely wrong in the interpretation of the (terse) Keychron documentation.
