### ISSUE TITLE
Keychron K3E1 confirmed working with Linux

### ISSUE THREAD

**Issue by sergetensen** [adam-savard/keychron-k2-function-keys-linux#23]
I tested with Kali on a Raspberry Pi 4. turning on and of through reboots keeps the F-keys working as expected. Turning F5 & F6 on and of with Fn + K + C (4 sec) also works.

Hope this helps.

//Serge

**Comment by adam-savard** [comment]
Thanks for the heads up! I'll add that to the readme!
