### ISSUE TITLE
Didn't work on boot.

### ISSUE THREAD

**Issue by terrencetec** [adam-savard/keychron-k2-function-keys-linux#3]
Hi,

I recently bought a Keychron K1 V4 and found your guide on how to restore the function keys. I know you said it's for K2 but I figured it should work for any other Keychron keyboards like mine and any other apple keyboards in general. It's great and it works when I type `systemctl start keychron` manually. However, it couldn't be automatically start on boot. Here is the error message I copied from journalctl.
```
Nov 28 13:21:01 Arch-AMD systemd[1]: Starting The command to make the Keychron K2 work...
Nov 28 13:21:01 Arch-AMD bash[504]: /bin/bash: /sys/module/hid_apple/parameters/fnmode: No such file or directory
Nov 28 13:21:01 Arch-AMD systemd[1]: keychron.service: Main process exited, code=exited, status=1/FAILURE
Nov 28 13:21:01 Arch-AMD systemd[1]: keychron.service: Failed with result 'exit-code'.
Nov 28 13:21:01 Arch-AMD systemd[1]: Failed to start The command to make the Keychron K2 work.
``` 
I am still a newbie in Linux so I am not sure what is the correct way to fix this. I found some other guides online which work well with apple keyboards, and it seems to me it's a simpler way. Here is way worked for me:
I created a file `/etc/modprobe.d/hid_apple.conf` and here is the content inside:
```
# /etc/modprobe.d/hid_apple.conf
option hid_apple fnmode=0
```

**Comment by ryanlaws** [comment]
I'm having the same issue with the K2 on Arch Linux.

**Comment by fetidd** [comment]
Yeah I'm getting same issue, also on Arch (EndeavourOS)

**Comment by martinmose** [comment]
I have the same issue as well - Ubuntu 20.04.2.0 LTS

@thekenu you forgot a "s" on options.

This is what worked for me:

`sudo nano /etc/modprobe.d/hid_apple.conf`

Insert:
`options hid_apple fnmode=2`

Save the file and exit, then run:
`sudo update-initramfs -u && reboot`

**Comment by adam-savard** [comment]
Since there appears to be a solution here, I'll be closing the issue.

Strange that some folks are having issues on boot... I haven't encountered that at all, though I should mention that I run Mint as my primary OS, so perhaps there's a change to how things work? Hard to say.
