### ISSUE TITLE
Automatic bash script to install the script

### ISSUE THREAD

**Issue by fuad-ardiono** [adam-savard/keychron-k2-function-keys-linux#4]
Requirement:
- User just run bash script to install and remove
- Update docs for script

**Comment by fuad-ardiono** [comment]
Hi @adam-savard i have just make PR for this issue

**Comment by adam-savard** [comment]
Sorry for the slow response here, life has a way of getting in the way!

I appreciate the effort that's gone into this, but I think having install/uninstall as another layer of abstraction to this when it's a one-line command in the script is making more work for the user. I'd rather have someone understand what they're doing and where something lives.
