### ISSUE TITLE
no need for service, same can be accomplished with grub2-mkconfig

### ISSUE THREAD

**Issue by smartbit** [adam-savard/keychron-k2-function-keys-linux#6]
## Fedora   
```shell
modinfo hid_apple | egrep "^parm" # view available parameters
echo "options hid_apple fnmode=2 swap_opt_cmd=1" > /etc/modprobe.d/hid_apple.conf
sudo modprobe -r hid_apple ; sudo modprobe -v hid_apple
cat /sys/module/hid_apple/parameters/{fnmode,swap_opt_cmd} 
sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
 ```
after  `reboot` verify status with `cat /sys/module/hid_apple/parameters/{fnmode,swap_opt_cmd}`

## Ubuntu
[Apply parameters](https://superuser.com/a/259340) using `sudo update-initramfs -u`

**Comment by adam-savard** [comment]
EDIT: see below reply

**Comment by mathetes87** [comment]
Messing with grub doesn't sound very wise for this particular use case. Systemd seems a better path IMHO

**Comment by adam-savard** [comment]
Messing with grub is very neat; as I've had time to think on it, though, I think systemd is much easier for new users. The same thing can be achieved through a cron job or anything else that runs commands at boot, but systemd is what the vast majority of folks are running right now. 

Messing around with the bootloader isn't something I'd recommend for anyone as fixing issues with it, if there are mistyped commands, might be out of someone's area of troubleshooting.

I'm going to close the issue, though I'm sure a google search will bring it back for anyone interested.
