### ISSUE TITLE
This script is only tested and validated on the K2

### ISSUE THREAD

**Issue by adam-savard** [adam-savard/keychron-k2-function-keys-linux#9]
This is more of a notification to anyone that comes across the repo with another keyboard model from Keychron, like the K1. Unless someone can chime in that this fixes all issues with all their keyboards then I wouldn't assume this script works.

That said, it won't actually hurt anything if you give the actual line of bash a try in the terminal. It would be reset on reboot.

**Comment by panmona** [comment]
It didn't work with that bash line from the README for me for the K2.
I used this instead:
`ExecStart=sudo bash -c "echo 0 > /sys/module/hid_apple/parameters/fnmode"`

But somehow in some cases this is not working, I get: No such file or directory.

**Comment by Helbis** [comment]
I tested it on Keychron K3, it works without problems.

**Comment by fmarilao** [comment]
tested on Keychron K6, it works !

**Comment by adam-savard** [comment]
I can add the keyboards listed here as tested to the readme; thanks for trying it out!

**Comment by m0ppers** [comment]
K1 SE works too :+1:

**Comment by elisauco** [comment]
Works on K8

**Comment by adam-savard** [comment]
Thanks everyone! These keyboards have been added to the readme. Ping me if there are others.

**Comment by sadikhasan1** [comment]
Thank you so much. Works on dareu A87 V2.
